### ISSUE TITLE
Support for macOS13 ventura

### ISSUE THREAD

**Issue by ravichaudhary133** [AbhaySingh15/Acer-aspire-7-A715-75G-Opencore-EFI#3]
Can we upgrade to macOS 13 ventura with this EFI?!

**Comment by AbhaySingh15** [comment]
I haven't tested ventura update yet so can't really say anything about it but you can update to monterey directly, just replace itlwm kext for big sur with monterey one.
Bluetooth doesn't work for me on monterey though that is why i am currently on big sur.
