### ISSUE TITLE
Which method did you follow to dual boot with windows?

### ISSUE THREAD

**Issue by shubham1358** [AbhaySingh15/Acer-aspire-7-A715-75G-Opencore-EFI#4]
Did you follow open Core guide for dual boot or something else? Can you help me with steps?
Thanks

**Comment by AbhaySingh15** [comment]
https://www.insanelymac.com/forum/topic/346365-guide-dual-boot-for-windows-1011-and-macos-on-the-same-disk-windows-installed-first-macos-installed-first-empty-drive/
