### ISSUE TITLE
MacOS Monterey Update

### ISSUE THREAD

**Issue by furkanardagul** [AbhaySingh15/Acer-aspire-7-A715-75G-Opencore-EFI#5]
I am currently using the i5-10300H of the same model. With this EFI, Big Sur was actively working. I want to try it for macOS Monterey, but I have files that I can lose, I wanted to get your opinion. Should I install it? My installation is in an important situation for my development.

**Comment by AbhaySingh15** [comment]
I am not maintaining this project anymore so can't really comment but you if you want to test it then i would recommend to use an external drive for experiments and test installation.
